- action:
  - service: cover.close_cover
    entity_id: cover.right_garage_door
  alias: Close right garage door after being left open
  id: '1520196242326'
  trigger:
  - entity_id: cover.right_garage_door
    platform: state
    to: open
    for:
      minutes: 15
- action:
  - service: cover.close_cover
    entity_id: cover.left_garage_door
  alias: Close left garage door after being left open
  id: '1520196242369'
  trigger:
  - entity_id: cover.left_garage_door
    platform: state
    to: open
    for:
      minutes: 15
- action:
  - service: light.turn_on
    entity_id: light.kitchen_led_strip
  alias: Turn on the kitchen LED strip when there's motion
  condition: []
  id: '1521847317798'
  trigger:
  - entity_id: sensor.kitchen_motion_sensor
    platform: state
    to: 'true'
- action:
  - service: light.turn_off
    entity_id: light.kitchen_led_strip
  alias: Turn off the kitchen LED strip when there's no motion
  condition: []
  id: '1521847692368'
  trigger:
  - entity_id: sensor.kitchen_motion_sensor
    platform: state
    to: 'false'
    for:
      minutes: 10
- id: '1529346024931'
  alias: Set Theme
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: dark_theme
    service: frontend.set_theme
- id: letsencrypt-renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: '1538364923368'
  alias: Turn on heater in the morning
  trigger:
  - at: 07:00:00
    platform: time
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.downstairs_bathroom_heater
- id: '1538365811855'
  alias: Turn off the heater in the morning
  trigger:
  - at: 08:00:00
    platform: time
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.downstairs_bathroom_heater
- id: '1540918848186'
  alias: Notify on HA Update
  trigger:
  - entity_id: updater.updater
    platform: state
  condition: []
  action:
  - data:
      event: ha_notify
      value1: 'Home Assistant {{ states.updater.updater.state }} is now available. '
    service: ifttt.trigger
- id: '1546789835044'
  alias: Notify if Left Garage Door Open > 1hr
  trigger:
  - entity_id: cover.left_garage_door
    for: '1:00:00'
    platform: state
    to: open
  condition: []
  action:
  - data:
      event: ha_notify
      value1: The left garage door has been open for an hour
    service: ifttt.trigger
- id: '1546789895121'
  alias: Notify if Right Garage Door Open > 1hr
  trigger:
  - entity_id: cover.right_garage_door
    for: '1:00:00'
    platform: state
    to: open
  condition: []
  action:
  - data:
      event: ha_notify
      value1: The right garage door has been open for an hour
    service: ifttt.trigger
