homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 274
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend: 
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
#logbook:
recorder:

# Track the sun
sun:

sensor: !include ./configuration/sensor.yaml

# Use the mosquito mqtt broker
mqtt:
  broker: 192.168.42.5
  discovery: true
  discovery_prefix: homeassistant
  username: !secret mqtt_user
  password: !secret mqtt_pass

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - group
  entity_config:
    switch.living_room_display_case:
      name: Moon Lights
      expose: true
      room: Living Room
    light.living_room_lamp:
      name: Living Room Lamp
      expose: true
      room: Living Room

tradfri:
  host: 192.168.42.20

speedtestdotnet:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Track devices!
device_tracker: !include configuration/device_tracker.yaml

# Garage config
cover: !include ./configuration/cover.yaml

light: !include ./configuration/light.yaml

switch: !include ./configuration/switch.yaml

ifttt:
  key: !secret ifttt_key

