# This is a load bearing setting
default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:
  ignore:
    - google_cast

device_tracker:

recorder:

sensor: !include ./configuration/sensor.yaml

# Use the mosquito mqtt broker
mqtt:
  sensor: !include ./configuration/sensor_mqtt.yaml
  switch: !include ./configuration/switch_mqtt.yaml
  switch: !include ./configuration/cover_mqtt.yaml
  switch: !include ./configuration/light_mqtt.yaml

# FIXME: We have to reconfigure this :(
#google_assistant: !include ./configuration/google_assistant.yaml

# ikea smarthome stuff, enable when in use
#tradfri:
#  host: !secret tradfri_ip

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

switch: !include ./configuration/switch.yaml
light: !include ./configuration/light.yaml
camera: !include ./configuration/camera.yaml

ifttt:
  key: !secret ifttt_key

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api_key

python_script:

api:

shell_command:
  dim_desktop: !secret dim_desktop_command
  toggle_mic: !secret toggle_mic_command
  toggle_camera: !secret toggle_camera_command
