homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 274
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
  - platform: yr
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - icon
    update_inverval:
      minutes: 30
  - platform: mqtt
    name: "Kitchen Motion Sensor"
    state_topic: "home/kitchen/motion-sensor"

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Track devices!
device_tracker:
  - platform: ddwrt
    host: !secret router_host
    username: !secret router_user
    password: !secret router_pass

# Enable built in mqtt broker
mqtt:
    port: 1883
    username: !secret mqtt_user
    password: !secret mqtt_pass

# Garage config
cover: !include ./configuration/cover.yaml

light: !include ./configuration/light.yaml

ifttt:
  key: !secret ifttt_key
