#- platform: ffmpeg
#  name: Garage Stream
#  input: !secret garage_camera_uri

- platform: generic
  name: Xena Cam
  username: root
  password: !secret xena_camera_password
  authentication: basic
  still_image_url: !secret xena_camera_uri
  verify_ssl: false
  scan_interval: 5
