esphome:
  name: bathroom_esp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

api:

ota:
  password: !secret ota_password

uart:
  rx_pin: RX
  baud_rate: 4800 

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

sensor:
  - platform: cse7766
    update_interval: 5s
    power:
      name: "Hairdryer Power"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Hairdryer Button"
    on_press:
      - switch.toggle: hairdryer

switch:
  - platform: gpio
    pin: GPIO12
    name: "Hairdryer"
    id: hairdryer

status_led:
  pin:
    number: GPIO13
    inverted: yes