esphome:
  name: desk_macros
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

http_request:
  useragent: esphome/device
  timeout: 10s

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: "Button 1"
    on_press:
      then:
        - mqtt.publish:
            topic: wled/desk
            payload: "T"
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: "Button 2"
    on_press:
      then:
        - homeassistant.event:
            event: esphome.desk_macros
            data:
              button: '2'
              presses: '1'
    on_double_click:
      then:
        - homeassistant.event:
            event: esphome.desk_macros
            data:
              button: '2'
              presses: '2'
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
    name: "Button 3"
    on_press:
      then:
        - http_request.post:
            url: !secret printer_api_url_command
            headers:
              Content-Type: application/json
              X-Api-Key: !secret printer_api_key
            body: '{"commands": ["M104 S0", "M140 S0"]}'
    on_double_click:
      then:
        - http_request.post:
            url: !secret printer_api_url_command
            headers:
              Content-Type: application/json
              X-Api-Key: !secret printer_api_key
            body: '{"commands": ["M104 S200", "M140 S60"]}'